### ISSUE TITLE
.gitignore の内容

### ISSUE THREAD

**Issue by stein2nd** [jawordpressorg/developer-plugins-handbook#16]
「package-lock.json」は、「npm install」の結果、各自のローカル環境に生成されるので、「.gitignore」に追加した方が良いのでは？

**Comment by t-hamano** [comment]
>「package-lock.json」は、「npm install」の結果、各自のローカル環境に生成されるので

これは正しいと思いますが、`package-lock.json` は依存関係を管理するために必要です。
また`npm install` を実行したとしても、必ずしも `package-lock.json` が更新されるとは限らず、npm のバージョンによって左右されると思います。

参考：https://bufferings.hatenablog.com/entry/2023/03/15/215044

`package-lock.json` ファイルをgit管理するかどうかはそのプロジェクトの性質によると思いますが、WordPressコアとGutenbergではgit管理されているので、それに従っています。

`npm ci` を実行してはどうでしょうか。

**Comment by t-hamano** [comment]
こちらはクローズさせていただきますが、もし他に提案とうありましたらいつでもコメントください。
