### ISSUE TITLE
wordpress-org/plugin-developer-faq/index.md 地の文から、見出しに変更

### ISSUE THREAD

**Issue by stein2nd** [jawordpressorg/developer-plugins-handbook#173]
中見出し「プラグイン名」配下の
「企業が私のパーマリンクに、その企業の商標を使用する許可を与えてくれることはありますか ?」は、見出しであることが妥当

**Comment by t-hamano** [comment]
https://github.com/jawordpressorg/developer-plugins-handbook/commit/4dd6fc27e7cfee6c371ff23ceb91233f556e54e9 で、日本語版リポジトリをアップストリームとして同期したときに修正済。
