### ISSUE TITLE
wordpress-org/index.md 原文との差分発見

### ISSUE THREAD

**Issue by stein2nd** [jawordpressorg/developer-plugins-handbook#177]
原文13行目　挿入された

**Comment by t-hamano** [comment]
https://github.com/jawordpressorg/developer-plugins-handbook/commit/4dd6fc27e7cfee6c371ff23ceb91233f556e54e9 で、日本語版リポジトリをアップストリームとして同期。新しいTracking Issue (https://github.com/jawordpressorg/developer-plugins-handbook/issues/185) の一部としてタスク管理します。
