### ISSUE TITLE
wordpress-org/how-to-use-subversion/index.md 原文との差分発見

### ISSUE THREAD

**Issue by stein2nd** [jawordpressorg/developer-plugins-handbook#178]
原文43行目　削除された
原文44行目　挿入された
原文90行目　タイポ修正された？

**Comment by t-hamano** [comment]
https://github.com/jawordpressorg/developer-plugins-handbook/commit/4dd6fc27e7cfee6c371ff23ceb91233f556e54e9 で、日本語版リポジトリをアップストリームとして同期したときに修正済。
