### ISSUE TITLE
wordpress-org/common-issues/index.md フォルダごと追加された

### ISSUE THREAD

**Issue by stein2nd** [jawordpressorg/developer-plugins-handbook#179]

**Comment by t-hamano** [comment]
https://github.com/jawordpressorg/developer-plugins-handbook/commit/4dd6fc27e7cfee6c371ff23ceb91233f556e54e9 で、日本語版リポジトリをアップストリームとして同期。これは新規ページであるため、 新しいTracking Issue (#185) の一部としてタスク管理します。
