### ISSUE TITLE
wordpress-org/special-user-roles-capabilities/index.md 画像リンクの代替テキストなどの見直し

### ISSUE THREAD

**Issue by stein2nd** [jawordpressorg/developer-plugins-handbook#365]
原文 17 行目、和訳 19 行目
原文 37 行目、和訳 39 行目
原文 52 行目、和訳 54 行目
原文 77 行目、和訳 79 行目
原文 107 行目、和訳 109 行目
原文では代替テキストを特に設定してないが、スクリーンリーダー対応の観点では、何か記載した方が良いのでは？
※issue #364 同様

**Comment by t-hamano** [comment]
ページ毎にissue/PRが立つと非常に数が多くなってしまうので、https://github.com/jawordpressorg/developer-plugins-handbook/issues/366 に統合しましょう。
